/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fema.squidclient.telas;

import br.edu.fema.squidclient.service.*;

import javax.swing.*;
import java.util.stream.Collectors;

public class MenuPrincipal extends javax.swing.JFrame {

    private final AuthUserSquidService authUserService;
    private final BlackListSquidService blackListService;
    private final CacheSizeSquidService cacheSquidService;
    private final FileExtensionSquidService fileExtService;
    private final TimeRuleSquidService timeRuleService;
    private final WhiteListSquidService whiteListService;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem blackListExtFlush;
    private javax.swing.JMenuItem blackListExtList;
    private javax.swing.JMenuItem blackListExtRemove;
    private javax.swing.JMenuItem blackListExtlAdd;
    private javax.swing.JMenu extBlackList;

    public MenuPrincipal(String url) {
        authUserService = new AuthUserSquidService(url);
        blackListService = new BlackListSquidService(url);
        cacheSquidService = new CacheSizeSquidService(url);
        fileExtService = new FileExtensionSquidService(url);
        timeRuleService = new TimeRuleSquidService(url);
        whiteListService = new WhiteListSquidService(url);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        blackListMenu = new javax.swing.JMenu();
        ipBlacklistMenu = new javax.swing.JMenu();
        blackListIpAdd = new javax.swing.JMenuItem();
        blackListIpRemove = new javax.swing.JMenuItem();
        blackListIpList = new javax.swing.JMenuItem();
        blackListIpFlush = new javax.swing.JMenuItem();
        urlBlackListMenu = new javax.swing.JMenu();
        blackListUrlAdd = new javax.swing.JMenuItem();
        blackListUrlRemove = new javax.swing.JMenuItem();
        blackListUrlList = new javax.swing.JMenuItem();
        blackListUrlFlush = new javax.swing.JMenuItem();
        extBlackList = new javax.swing.JMenu();
        blackListExtlAdd = new javax.swing.JMenuItem();
        blackListExtRemove = new javax.swing.JMenuItem();
        blackListExtList = new javax.swing.JMenuItem();
        blackListExtFlush = new javax.swing.JMenuItem();
        whiteListMenu = new javax.swing.JMenu();
        ipWhiteListMenu = new javax.swing.JMenu();
        whiteListIpAdd = new javax.swing.JMenuItem();
        whiteListIpRemove = new javax.swing.JMenuItem();
        whiteListIpList = new javax.swing.JMenuItem();
        whiteListIpFlush = new javax.swing.JMenuItem();
        urlWhiteListMenu = new javax.swing.JMenu();
        whiteListUrlAdd = new javax.swing.JMenuItem();
        whiteListUrlRemove = new javax.swing.JMenuItem();
        whiteListUrlList = new javax.swing.JMenuItem();
        whiteListUrlFlush = new javax.swing.JMenuItem();
        usuariosMenu = new javax.swing.JMenu();
        usuarioAdd = new javax.swing.JMenuItem();
        usuarioRemove = new javax.swing.JMenuItem();
        usuarioList = new javax.swing.JMenuItem();
        usuarioFlush = new javax.swing.JMenuItem();
        timeRuleMenu = new javax.swing.JMenu();
        timeRuleAdd = new javax.swing.JMenuItem();
        timeRuleRemove = new javax.swing.JMenuItem();
        timeRuleList = new javax.swing.JMenuItem();
        timeRuleFlush = new javax.swing.JMenuItem();
        cacheMenu = new javax.swing.JMenu();
        cacheSizeAdd = new javax.swing.JMenuItem();
        cacheSizeFlush = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        blackListMenu.setMnemonic('f');
        blackListMenu.setText("Blacklist");

        ipBlacklistMenu.setText("IP");

        blackListIpAdd.setText("Adicionar");
        ipBlacklistMenu.add(blackListIpAdd);

        blackListIpRemove.setText("Remover");
        ipBlacklistMenu.add(blackListIpRemove);

        blackListIpList.setText("Listar");
        blackListIpList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackListIpListActionPerformed(evt);
            }
        });
        ipBlacklistMenu.add(blackListIpList);

        blackListIpFlush.setText("Limpar tudo");
        blackListIpFlush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackListIpFlushActionPerformed(evt);
            }
        });
        ipBlacklistMenu.add(blackListIpFlush);

        blackListMenu.add(ipBlacklistMenu);

        urlBlackListMenu.setText("URL");

        blackListUrlAdd.setText("Adicionar");
        urlBlackListMenu.add(blackListUrlAdd);

        blackListUrlRemove.setText("Remover");
        urlBlackListMenu.add(blackListUrlRemove);

        blackListUrlList.setText("Listar");
        blackListUrlList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackListUrlListActionPerformed(evt);
            }
        });
        urlBlackListMenu.add(blackListUrlList);

        blackListUrlFlush.setText("Limpar tudo");
        blackListUrlFlush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackListUrlFlushActionPerformed(evt);
            }
        });
        urlBlackListMenu.add(blackListUrlFlush);

        blackListMenu.add(urlBlackListMenu);

        extBlackList.setText("Extensão");

        blackListExtlAdd.setText("Adicionar");
        extBlackList.add(blackListExtlAdd);

        blackListExtRemove.setText("Remover");
        extBlackList.add(blackListExtRemove);

        blackListExtList.setText("Listar");
        blackListExtList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackListExtListActionPerformed(evt);
            }
        });
        extBlackList.add(blackListExtList);

        blackListExtFlush.setText("Limpar tudo");
        blackListExtFlush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackListExtFlushActionPerformed(evt);
            }
        });
        extBlackList.add(blackListExtFlush);

        blackListMenu.add(extBlackList);

        menuBar.add(blackListMenu);

        whiteListMenu.setMnemonic('e');
        whiteListMenu.setText("Whitelist");

        ipWhiteListMenu.setText("IP");

        whiteListIpAdd.setText("Adicionar");
        ipWhiteListMenu.add(whiteListIpAdd);

        whiteListIpRemove.setText("Remover");
        ipWhiteListMenu.add(whiteListIpRemove);

        whiteListIpList.setText("Listar");
        whiteListIpList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteListIpListActionPerformed(evt);
            }
        });
        ipWhiteListMenu.add(whiteListIpList);

        whiteListIpFlush.setText("Limpar tudo");
        whiteListIpFlush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteListIpFlushActionPerformed(evt);
            }
        });
        ipWhiteListMenu.add(whiteListIpFlush);

        whiteListMenu.add(ipWhiteListMenu);

        urlWhiteListMenu.setText("URL");

        whiteListUrlAdd.setText("Adicionar");
        urlWhiteListMenu.add(whiteListUrlAdd);

        whiteListUrlRemove.setText("Remover");
        urlWhiteListMenu.add(whiteListUrlRemove);

        whiteListUrlList.setText("Listar");
        whiteListUrlList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteListUrlListActionPerformed(evt);
            }
        });
        urlWhiteListMenu.add(whiteListUrlList);

        whiteListUrlFlush.setText("Limpar tudo");
        whiteListUrlFlush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteListUrlFlushActionPerformed(evt);
            }
        });
        urlWhiteListMenu.add(whiteListUrlFlush);

        whiteListMenu.add(urlWhiteListMenu);

        menuBar.add(whiteListMenu);

        usuariosMenu.setMnemonic('h');
        usuariosMenu.setText("Usuarios");

        usuarioAdd.setText("Adicionar");
        usuariosMenu.add(usuarioAdd);

        usuarioRemove.setText("Remover");
        usuariosMenu.add(usuarioRemove);

        usuarioList.setText("Listar");
        usuarioList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioListActionPerformed(evt);
            }
        });
        usuariosMenu.add(usuarioList);

        usuarioFlush.setText("Limpar tudo");
        usuarioFlush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioFlushActionPerformed(evt);
            }
        });
        usuariosMenu.add(usuarioFlush);

        menuBar.add(usuariosMenu);

        timeRuleMenu.setText("Regra de tempo");

        timeRuleAdd.setText("Adicionar");
        timeRuleMenu.add(timeRuleAdd);

        timeRuleRemove.setText("Remover");
        timeRuleMenu.add(timeRuleRemove);

        timeRuleList.setText("Listar");
        timeRuleList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeRuleListActionPerformed(evt);
            }
        });
        timeRuleMenu.add(timeRuleList);

        timeRuleFlush.setText("Limpar tudo");
        timeRuleFlush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeRuleFlushActionPerformed(evt);
            }
        });
        timeRuleMenu.add(timeRuleFlush);

        menuBar.add(timeRuleMenu);

        cacheMenu.setText("Cache");

        cacheSizeAdd.setText("Configurar");
        cacheMenu.add(cacheSizeAdd);

        cacheSizeFlush.setText("Limpar");
        cacheSizeFlush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cacheSizeFlushActionPerformed(evt);
            }
        });
        cacheMenu.add(cacheSizeFlush);

        menuBar.add(cacheMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blackListIpFlushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackListIpFlushActionPerformed
        Integer result = JOptionPane.showConfirmDialog(null, "Deseja mesmo limpar tudo?", "Deseja mesmo limpar tudo?", JOptionPane.YES_NO_OPTION);
        if (result.equals(JOptionPane.YES_OPTION)) {
            blackListService.flushIp();
        }
    }//GEN-LAST:event_blackListIpFlushActionPerformed

    private void blackListUrlFlushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackListUrlFlushActionPerformed
        Integer result = JOptionPane.showConfirmDialog(null, "Deseja mesmo limpar tudo?", "Deseja mesmo limpar tudo?", JOptionPane.YES_NO_OPTION);
        if (result.equals(JOptionPane.YES_OPTION)) {
            blackListService.flushUrl();
        }
    }//GEN-LAST:event_blackListUrlFlushActionPerformed

    private void whiteListIpFlushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteListIpFlushActionPerformed
        Integer result = JOptionPane.showConfirmDialog(null, "Deseja mesmo limpar tudo?", "Deseja mesmo limpar tudo?", JOptionPane.YES_NO_OPTION);
        if (result.equals(JOptionPane.YES_OPTION)) {
            whiteListService.flushIp();
        }
    }//GEN-LAST:event_whiteListIpFlushActionPerformed

    private void whiteListUrlFlushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteListUrlFlushActionPerformed
        Integer result = JOptionPane.showConfirmDialog(null, "Deseja mesmo limpar tudo?", "Deseja mesmo limpar tudo?", JOptionPane.YES_NO_OPTION);
        if (result.equals(JOptionPane.YES_OPTION)) {
            whiteListService.flushUrl();
        }
    }//GEN-LAST:event_whiteListUrlFlushActionPerformed

    private void blackListIpListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackListIpListActionPerformed
        String resultado = blackListService.listIp().stream().collect(Collectors.joining("\n", "Resultado da consulta:", ""));
        JOptionPane.showMessageDialog(null, resultado);
    }//GEN-LAST:event_blackListIpListActionPerformed

    private void blackListUrlListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackListUrlListActionPerformed
        String resultado = blackListService.listUrl().stream().collect(Collectors.joining("\n", "Resultado da consulta:", ""));
        JOptionPane.showMessageDialog(null, resultado);
    }//GEN-LAST:event_blackListUrlListActionPerformed

    private void whiteListIpListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteListIpListActionPerformed
        String resultado = whiteListService.listIp().stream().collect(Collectors.joining("\n", "Resultado da consulta:", ""));
        JOptionPane.showMessageDialog(null, resultado);
    }//GEN-LAST:event_whiteListIpListActionPerformed

    private void whiteListUrlListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteListUrlListActionPerformed
        String resultado = whiteListService.listUrl().stream().collect(Collectors.joining("\n", "Resultado da consulta:", ""));
        JOptionPane.showMessageDialog(null, resultado);
    }//GEN-LAST:event_whiteListUrlListActionPerformed

    private void blackListExtListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackListExtListActionPerformed
        String resultado = fileExtService.listar().stream().collect(Collectors.joining("\n", "Resultado da consulta:", ""));
        JOptionPane.showMessageDialog(null, resultado);
    }//GEN-LAST:event_blackListExtListActionPerformed

    private void blackListExtFlushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackListExtFlushActionPerformed
        Integer result = JOptionPane.showConfirmDialog(null, "Deseja mesmo limpar tudo?", "Deseja mesmo limpar tudo?", JOptionPane.YES_NO_OPTION);
        if (result.equals(JOptionPane.YES_OPTION)) {
            fileExtService.flush();
        }
    }//GEN-LAST:event_blackListExtFlushActionPerformed

    private void usuarioListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioListActionPerformed
        String resultado = authUserService.listar().stream().map(au -> au.getCodigo() + " - " + au.getUsername()).collect(Collectors.joining("\n", "Resultado da consulta:", ""));
        JOptionPane.showMessageDialog(null, resultado);
    }//GEN-LAST:event_usuarioListActionPerformed

    private void usuarioFlushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioFlushActionPerformed
        Integer result = JOptionPane.showConfirmDialog(null, "Deseja mesmo limpar tudo?", "Deseja mesmo limpar tudo?", JOptionPane.YES_NO_OPTION);
        if (result.equals(JOptionPane.YES_OPTION)) {
            authUserService.flush();
        }
    }//GEN-LAST:event_usuarioFlushActionPerformed

    private void timeRuleListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeRuleListActionPerformed
        String resultado = timeRuleService.listar().stream().map((timeRule) -> timeRule.toString()).collect(Collectors.joining("\n", "Resultado da consulta:", ""));
        JOptionPane.showMessageDialog(null, resultado);
    }//GEN-LAST:event_timeRuleListActionPerformed

    private void timeRuleFlushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeRuleFlushActionPerformed
        Integer result = JOptionPane.showConfirmDialog(null, "Deseja mesmo limpar tudo?", "Deseja mesmo limpar tudo?", JOptionPane.YES_NO_OPTION);
        if (result.equals(JOptionPane.YES_OPTION)) {
            timeRuleService.flush();
        }
    }//GEN-LAST:event_timeRuleFlushActionPerformed
    private javax.swing.JMenuItem blackListIpAdd;
    private javax.swing.JMenuItem blackListIpFlush;
    private javax.swing.JMenuItem blackListIpList;
    private javax.swing.JMenuItem blackListIpRemove;
    private javax.swing.JMenu blackListMenu;
    private javax.swing.JMenuItem blackListUrlAdd;
    private javax.swing.JMenuItem blackListUrlFlush;
    private javax.swing.JMenuItem blackListUrlList;
    private javax.swing.JMenuItem blackListUrlRemove;
    private javax.swing.JMenu cacheMenu;
    private javax.swing.JMenuItem cacheSizeAdd;
    private javax.swing.JMenuItem cacheSizeFlush;

    private void cacheSizeFlushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cacheSizeFlushActionPerformed
        Integer result = JOptionPane.showConfirmDialog(null, "Deseja mesmo limpar tudo?", "Deseja mesmo limpar tudo?", JOptionPane.YES_NO_OPTION);
        if (result.equals(JOptionPane.YES_OPTION)) {
            cacheSquidService.reset();
        }
    }//GEN-LAST:event_cacheSizeFlushActionPerformed
    private javax.swing.JMenu ipBlacklistMenu;
    private javax.swing.JMenu ipWhiteListMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem timeRuleAdd;
    private javax.swing.JMenuItem timeRuleFlush;
    private javax.swing.JMenuItem timeRuleList;
    private javax.swing.JMenu timeRuleMenu;
    private javax.swing.JMenuItem timeRuleRemove;
    private javax.swing.JMenu urlBlackListMenu;
    private javax.swing.JMenu urlWhiteListMenu;
    private javax.swing.JMenuItem usuarioAdd;
    private javax.swing.JMenuItem usuarioFlush;
    private javax.swing.JMenuItem usuarioList;
    private javax.swing.JMenuItem usuarioRemove;
    private javax.swing.JMenu usuariosMenu;
    private javax.swing.JMenuItem whiteListIpAdd;
    private javax.swing.JMenuItem whiteListIpFlush;
    private javax.swing.JMenuItem whiteListIpList;
    private javax.swing.JMenuItem whiteListIpRemove;
    private javax.swing.JMenu whiteListMenu;
    private javax.swing.JMenuItem whiteListUrlAdd;
    private javax.swing.JMenuItem whiteListUrlFlush;
    private javax.swing.JMenuItem whiteListUrlList;
    private javax.swing.JMenuItem whiteListUrlRemove;
    // End of variables declaration//GEN-END:variables

}
